LevelDB Config Setup
hyphacoop/api.distributed.press pull request #32
Opened 2022-12-05 00:31 UTC by jackyzha0

Closes #58

2022-12-05 17:10 UTC, RangerMauve requested changes
Looking good! Just a few comments about structure.

I'm liking how easy the sublevel stuff makes things, and the scehemas are useful to understand the data that's being sent around 💯

2022-12-05 17:13 UTC, jackyzha0 commented on v1/api/publisher.ts
> +  }, async (request, _reply) => {
Yeah mostly just as a reminder that it exists :') I expect we might use it at some point

2022-12-05 17:14 UTC, RangerMauve commented on v1/api/publisher.ts
> +  }, async (request, _reply) => {
Sounds good to me 👍

2022-12-06 17:40 UTC, RangerMauve approved these changes
Looks good to me 👍 Feel free to merge.

Your call on whether you want to merge this into staging first and then staging into v1, or staging into v1 then this into v1.

2022-12-06 17:42 UTC, merged