Protocol Integration
hyphacoop/api.distributed.press pull request #35
Opened 2023-01-16 00:54 UTC by jackyzha0

- API calls now hooks up with appropriate protocols based on config

2023-01-17 02:38 UTC, RangerMauve requested changes
Awesome! I like where this is going. Some minor nits but I think this is a better structure from before. sync vs unsync is good wording for it IMO.

@fauno Heads up, this changes the HTTP API a bit for updating site data.

2023-01-17 02:38 UTC, RangerMauve commented on v1/api/sites.ts
> +      body: ProtocolStatus,
Mind wrapping this in one more layer so that we can add more fields that can be added in the future? .e.g `Body: { protocols: ProtocolStatus}`

2023-01-17 02:38 UTC, RangerMauve commented on v1/config/sites.ts
> +      promises.push(await this.http.unsync(site.links.http))
Should get rid of the `await` if you're aiming to do these in paralel.

2023-01-17 02:38 UTC, RangerMauve commented on v1/fs/index.ts
> +    return await Promise.resolve(sitePath)
Should be able to just return `sitePath`. Is there a use for wrapping in an extra Promise?

2023-01-17 14:47 UTC, fauno commented
> @fauno Heads up, this changes the HTTP API a bit for updating site data.

Could you point me to those changes? I saw there's a change on NewSite and publication changed to a protocolos object of protocol: Boolean pairs?

2023-01-17 14:51 UTC, fauno commented on v1/config/sites.test.ts
>    domain: 'https://example.com',
i just noticed this, i was sending just example.com, which should it be?

2023-01-17 16:29 UTC, fauno commented
> Could you point me to those changes? I saw there's a change on NewSite and publication changed to a protocolos object of protocol: Boolean pairs?

Nevermind, I'm reading the files :)

2023-01-26 15:15 UTC, fauno commented
i'm having this tsc error when running `dev` script after the last commit, removing the whole block of sync code con v1/api/sites.ts works for the tests i was doing.

```
config/sites.ts(34,13): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index ty
pe '{ ipfs: boolean; hyper: boolean; http: boolean; }'.             
  No index signature with a parameter of type 'string' was found on type '{ ipfs: boolean; hyper: boolean; http: boolean; }'.
config/sites.ts(35,27): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index ty
pe 'ProtocolManager'.                                                                                                                   
  No index signature with a parameter of type 'string' was found on type 'ProtocolManager'.
config/sites.ts(37,20): error TS7006: Parameter 'protocolLinks' implicitly has an 'any' type.
config/sites.ts(38,15): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index ty
pe 'Partial<{ ipfs: { gateway: string; cid: string; pubKey: string; } & { link: string; enabled: boolean; }; hyper: { gateway: string; r
aw: string; } & { link: string; enabled: boolean; }; http: {} & { link: string; enabled: boolean; }; }>'.
  No index signature with a parameter of type 'string' was found on type 'Partial<{ ipfs: { gateway: string; cid: string; pubKey: string
; } & { link: string; enabled: boolean; }; hyper: { gateway: string; raw: string; } & { link: string; enabled: boolean; }; http: {} & { 
link: string; enabled: boolean; }; }>'.
```

not sure if this change affects the api endpoints, i'd have to adapt the client. it seems to work for a nanoid still, but not sure if internally it thinks it's the domain name

```js+diff
-    const id = nanoid()                                                                                                                
+    const id = cfg.domain                                                                                                              
```

2023-01-26 17:44 UTC, RangerMauve commented
Oh, I messed up some typescript types, working on fixing it now

2023-01-26 18:00 UTC, RangerMauve commented
Just gonna add some more fixes for the protocol stuff first

2023-01-26 18:01 UTC, RangerMauve commented
Make sure to do an `npm install` call after pulling.

2023-01-26 20:41 UTC, RangerMauve commented
Remaining steps:

- Wait for js-ipfs-http-client to update with the key gen fix: https://github.com/ipfs/js-ipfs/pull/4303
- Get a basic JS test for uploading Formdata using the new `site.tar.gz` fixture and the form-data module https://github.com/fastify/light-my-request/issues/35
- Fix js-ipfs-mfs-sync erroring due to Kubo not implementing `ipfs.files.touch`

2023-02-02 20:42 UTC, RangerMauve approved these changes
Other than the one nit pic I think this is good to go!

Mind addressing the comment and then merging in?

Also, I really like your approach of adding a context to tests for setup and teardown.

2023-02-02 20:42 UTC, RangerMauve commented on v1/config/sites.ts
> +      return await Promise.reject(new Error('Invalid hostname. Please ensure you leave out the port and protocol specifiers (e.g. no https://)'))
Does `throw` not work for this case? If it's a linter thing, I'd appreciate it if we could disable whatever rule is mandating this code style. :P

2023-02-02 21:46 UTC, merged