feat: add cron job to restart the service every few days
hyphacoop/api.distributed.press pull request #67
Opened 2023-10-10 19:22 UTC by akhileshthite

https://github.com/hyphacoop/distributed-press-organizing/issues/95

```
sudo ansible-playbook distributed_press.yml -i local_deploy.yml --tags cron
```
![Screenshot 2023-10-10 at 11 39 03 PM](https://github.com/hyphacoop/api.distributed.press/assets/68826419/ac05963c-e8dc-46bc-9ce9-02dd87bd45ee)

```
sudo crontab
```
![Screenshot 2023-10-10 at 11 39 40 PM](https://github.com/hyphacoop/api.distributed.press/assets/68826419/f1a0758a-4453-4415-a515-581f7981606f)

2023-10-10 19:33 UTC, akhileshthite commented
> [hyphacoop/distributed-press-organizing#95](https://github.com/hyphacoop/distributed-press-organizing/issues/95)
> 
> ```
> sudo ansible-playbook distributed_press.yml -i local_deploy.yml --tags cron
> ```
> 
> ![Screenshot 2023-10-10 at 11 39 03 PM](https://user-images.githubusercontent.com/68826419/274039522-ac05963c-e8dc-46bc-9ce9-02dd87bd45ee.png)
> 
> ```
> sudo crontab -l
> ```
> 
> ![Screenshot 2023-10-10 at 11 39 40 PM](https://user-images.githubusercontent.com/68826419/274039688-f1a0758a-4453-4415-a515-581f7981606f.png)

@RangerMauve 
I don't have a linux machine to test the `systemctl` command.
However, I adjusted the cron timing every minute for quicker testing to ensure the `systemctl` command works as expected.

Can you test this?
```
- name: "Test cron job to restart api.distributed.press service every minute"
  cron:
    name: "Restart api.distributed.press service"
    minute: "*"
    job: "/bin/systemctl restart {{ distributed_press_service_name }}"
  become: yes
  tags:
    - cron
```

```
sudo ansible-playbook distributed_press.yml -i local_deploy.yml --tags cron
```

2023-10-11 19:44 UTC, RangerMauve requested changes
Tested and it works. Mind checking if the template is still needed and removing it if not?

2023-10-11 19:44 UTC, RangerMauve commented on ansible/roles/distributed_press/templates/distributed_press_restart_cron.j2
> +* * */3 * * /bin/systemctl restart {{distributed_press_service_name}}
Is this file still needed?

2023-10-12 08:44 UTC, akhileshthite commented on ansible/roles/distributed_press/templates/distributed_press_restart_cron.j2
> +* * */3 * * /bin/systemctl restart {{distributed_press_service_name}}
No, removed.

2023-10-12 17:29 UTC, RangerMauve approved these changes

2023-10-12 17:29 UTC, merged