feat: set x-ipfs-path header
hyphacoop/api.distributed.press pull request #74
Opened 2024-02-26 18:58 UTC by fauno

closes #73

2024-02-26 19:23 UTC, RangerMauve requested changes

2024-02-27 13:13 UTC, fauno commented on ansible/roles/distributed_press/templates/nginx-static.j2
> +  add_header 'X-Ipfs-Path' '/ipns/$ssl_server_name';
done!

2024-02-27 13:13 UTC, fauno commented on ansible/roles/distributed_press/templates/nginx-site.j2
> +  add_header 'X-Ipfs-Path' '/ipns/$ssl_server_name';
done!

2024-02-27 21:20 UTC, RangerMauve commented
Cool let's give it a shot!

2024-02-27 21:20 UTC, merged